name: "\U0001F41B Bug report"

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description:
  Create a report to help us repair something that is currently broken

title: "[BUG]"

labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Use this template to raise issues about installing or running _The Turing Way_ locally on your computer. 

        If you would like to raise an issue about fixing typos, or formatting issues in chapters, please use the [Editor's Issue template](https://github.com/alan-turing-institute/the-turing-way/issues/new?assignees=&labels=&template=EDITOR_ISSUE_TEMPLATE.yml).

  - type: textarea
    attributes:
      label: Description
      description: |
        Use this section to clearly and concisely describe the bug.  

        We suggest using bullets (indicated by * or -) or checkboxes [ ] (filled checkbox [x]) here.
      value: |
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Tell us what you thought would happen. 

        We suggest using bullets (indicated by * or -) or checkboxes [ ] (filled checkbox [x]) here.
      value: |
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Actual behaviour
      description: |
        Tell us what actually happens. 

        We suggest using bullets (indicated by * or -) or checkboxes [ ] (filled checkbox [x]) here.
      value: |
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: How to reproduce
      description:
        Use this section to describe the steps that a user would take to
        experience this bug.
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error -->
      render: markdown
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Your personal set up

        Tell us a little about the system you're using or tested this bug in.

  - type: textarea
    attributes:
      label: Operating system
      description: |
        Such as linux or OSX. 

        We suggest using bullets (indicated by * or -) or checkboxes [ ] (filled checkbox [x]) here.
      value: |
        - [ ] OSX:
        - [ ] Linux:
        - [ ] Windows

      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Browser
      description: |
        Such as Chrome or Firefox.

        We suggest using bullets (indicated by * or -) or checkboxes [ ] (filled checkbox [x]) here.
      value: |
        - [ ] Chrome
        - [ ] Firefox
        - [ ] Safari

      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Dependencies
      description:
        Such as `jupyter-book` or  `datascience`. You can generate a list of
        this using `pip freeze` or `conda list` depending on the package manager
        you are using. YOU MAY SKIP THIS SECTION
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Failure Logs
      description:
        Please include any relevant log snippets or files here. You may also
        include screenshots.
    validations:
      required: false
